### ISSUE TITLE
fh_debug extension required for viewhelper?

### ISSUE THREAD

**Issue by lsascha** [opaque01/registeraddress_categories#1]
If i am correct, your viewhelpers require the fh_debug extension to be installed, since it calls the debug methods from this.

Since its not even included as requirement in the composer.json or ext_emconf.php, you should at least wrap the debug stuff with a
```
if (\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('fh_debug')) {
    // your debug stuff
}
```

**Comment by opaque01** [comment]
Hallo Isacha, feel free to write a pull request - so I will try to merge it to the code. (Please be patient, I am new to github).
opaque

**Comment by opaque01** [comment]
I have added your code. Thx
